### ISSUE TITLE
Why would you copy paste and publish as your own theme without attribution?

### ISSUE THREAD

**Issue by adityatelange** [charlola/hugo-theme-charlolamode#14]
This theme is a Copy of Papermod https://github.com/adityatelange/hugo-PaperMod
without giving proper attributions not stating the License.

https://github.com/charlola/hugo-theme-charlolamode/commit/4a183648bebd7c2ce565eae880d6dc3c09c6d9db#diff-1e893141c824fc9b6b689aa48d80c21f01d98510ab3d2cb84528447fd8563b04

Please republish it with proper attribution to its source or make it private.

**Comment by charlola** [comment]
Hey, thanks for raising this. I see your points and your arguments are fair. I **always** give people the credits and try mention everyone. This includes also the people in my podcast, for the companies I work for, my blogposts and LinkedIn posts. And again, also in this case I was giving credits to nanxiaobei. Sorry for not mentioning you. 

This hugo-blog was my very first programming project I did myself. Remember the time when you started your first project. In the beginning you are oblivious to a lot of facts and rules, but you are learning the more you invest time in it. I was just super happy that the new built-in features worked and about all the learnings I had. I wanted make this publicly available for everyone to use, not really being aware of how forks and licenses properly should be done. I haven’t collaborated too much, let alone published usable projects on GitHub before. 

So again, thanks for raising this and made this conversation a lesson learned. I will give you and nanxiaobei half of my Kofi donations for not forking properly. Apologies, Aditya. I just wanted to contribute to the community and make content available for everyone to use :) that’s also the reason why I started the podcast.
