### ISSUE TITLE
Projects

### ISSUE THREAD

**Issue by paarthtandon** [charlola/hugo-theme-charlolamode#4]
Hello,

Thank you for making this theme, I am currently working on my own personal site using it.

I noticed that on your personal site you have a projects section with different formatting that the articles section. Is this a part of the repo, and if so how do I use it? If its not I would love if you could update the repo to include it.

Thank you,
Paarth Tandon

**Comment by charlola** [comment]
Hey Paarth, 

Thanks for using this theme!

I'm happy to help, please try out the new feature 👍  If you like it, I'd be super happy to buy new books with your donation as I use my free time to build features 😄  [thank you for your donation :)](https://ko-fi.com/heycharlola)

**Comment by paarthtandon** [comment]
Thanks
