### ISSUE TITLE
Enable using theme as git submodule

### ISSUE THREAD

**Issue by IndrekHaav** [charlola/hugo-theme-charlolamode#6]
Right now this repo is structured as a Hugo site, which makes it tricky to integrate into existing projects. On the other hand, if you had the theme itself at the top level and the sample content in a separate directory, that would make it possible to use the theme as a git submodule, e.g.:

    git submodule add https://github.com/author/theme.git themes/theme-name

This is how most other Hugo themes I've looked at are structured. As an example: https://github.com/panr/hugo-theme-hello-friend

Would you consider restructuring your repo in this manner?

**Comment by charlola** [comment]
Hey Indrek! Thanks for hinting. Restructure is done. Enjoy building your website! :D

**Comment by charlola** [comment]
Please try it out and give me feedback. If there are still errors, let me know.

**Comment by IndrekHaav** [comment]
The config.yml file in the theme's directory seems to get added to the site's own config file. I think you'd need to move everything that's not used by the theme, into a separate subdirectory (e.g. "exampleSite").
