### ISSUE TITLE
404 when clicking on a page multiple times

### ISSUE THREAD

**Issue by Pranavmr009** [charlola/hugo-theme-charlolamode#7]
When we click on on a tab multiple times for example if I click on the about page twice it is redirecting to 
https://website.com/about/about which is returning a 404 error. This does not seem to happen when hosting locally but on any servers or hosting services like netlify this is happening. I think this is happening in your personal website as well

**Comment by edsoncelio** [comment]
Hi @Pranavmr009, I had this issue with Netlify (today), and It was because I didn't set the right `baseURL` in the config file.
