### ISSUE TITLE
[SOLVED] URL error when changing page/content

### ISSUE THREAD

**Issue by morales-alex** [charlola/hugo-theme-charlolamode#9]
Hi, have an issue with the URLs created by the menu. When click more than one menu link out of home page, my URL is not “https://example.com/content”, is “https://example.com/content/content-2”. Simplifying, the URL is added.

I managed to **fix** it by changing the URL of each content of the menu in config.yml. Following the instructions of [HUGO | Menus](https://gohugo.io/content-management/menus/#add-non-content-entries-to-a-menu)
e.g.
`- name: Contact
          url: contact/
          weight: 30`--> `- name: Contact
          url: /contact/
          weight: 30`
I add this to help if someone arrives the same error as me.
P.D: Thanks @charlola  for the theme, it's nice and easy to use. 
It has helped me create my first portfolio. Thank you.

**Comment by charlola** [comment]
Thank you for hinting about this, Alex! I added this in the config.yml to prevent this error.
